### ISSUE TITLE
Error loading plugin homebridge-hs100

### ISSUE THREAD

**Issue by hoveeman** [plasticrake/homebridge-hs100#1]
I'm trying to use the hs-100 plugin on my raspberry Pi 2. However I keep receiving these errors once I tried to add the hs-100 plugin. I have removed and reinstalled both homebridge and hs-100 and reinstalled.

I'm running homebridge 0.3.4 and node 5.12.0.

`pi@pi:/usr/local/lib/node_modules/homebridge-hs100 $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[7/18/2016, 11:03:37 PM] ====================
[7/18/2016, 11:03:37 PM] ERROR LOADING PLUGIN homebridge-hs100:
[7/18/2016, 11:03:37 PM] Error: Cannot find module 'Hs100-api'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hs100/index.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[7/18/2016, 11:03:37 PM] ====================
[7/18/2016, 11:03:39 PM] Loaded plugin: homebridge-ifttt
[7/18/2016, 11:03:39 PM] Registering platform 'homebridge-ifttt.IFTTT'
[7/18/2016, 11:03:39 PM] ---
[7/18/2016, 11:03:41 PM] Loaded plugin: homebridge-nest
[7/18/2016, 11:03:41 PM] Registering platform 'homebridge-nest.Nest'
[7/18/2016, 11:03:41 PM] ---
[7/18/2016, 11:03:41 PM] Loaded config.json with 0 accessories and 3 platforms.
[7/18/2016, 11:03:41 PM] ---
[7/18/2016, 11:03:41 PM] Loading 3 platforms...
[7/18/2016, 11:03:41 PM] [Nest] Initializing Nest platform...
[7/18/2016, 11:03:41 PM] [Nest] Fetching Nest devices.
/usr/local/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Hs100' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3`

**Comment by plasticrake** [comment]
Try upgrading to 1.1.1,  this should be fixed.
`npm update -g homebridge-hs100`
