### ISSUE TITLE
Plugin crashes homebridge

### ISSUE THREAD

**Issue by settingup** [plasticrake/homebridge-hs100#16]
I installed the hs-100 plugin, added the details to the config.json file but when I try to load home bridge the following error occurs:

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2/18/2017, 1:32:09 PM] Loaded plugin: homebridge-harmonyhub
[2/18/2017, 1:32:12 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2/18/2017, 1:32:12 PM] ---
[2/18/2017, 1:32:12 PM] Loaded plugin: homebridge-hs100
[2/18/2017, 1:32:12 PM] Registering platform 'homebridge-hs100.Hs100'
[2/18/2017, 1:32:12 PM] ---
[2/18/2017, 1:32:12 PM] Loaded plugin: homebridge-server
[2/18/2017, 1:32:12 PM] Registering platform 'homebridge-server.Server'
[2/18/2017, 1:32:12 PM] ---
[2/18/2017, 1:32:12 PM] Loaded plugin: homebridge-wol
[2/18/2017, 1:32:12 PM] Registering accessory 'homebridge-wol.Computer'
[2/18/2017, 1:32:12 PM] ---
[2/18/2017, 1:32:12 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/18/2017, 1:32:12 PM] ---
[2/18/2017, 1:32:12 PM] Loading 1 platforms...
[2/18/2017, 1:32:12 PM] [Harmony Hub] Initializing HarmonyHub platform...
Load homebridge-hs100.Hs100
/usr/lib/node_modules/homebridge-hs100/index.js:20
    this.plugs = config['plugs'] || [];
                       ^

TypeError: Cannot read property 'plugs' of null
    at new Hs100Platform (/usr/lib/node_modules/homebridge-hs100/index.js:20:24)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

My homebridge is working correctly when I uninstall the HS100 plugin. The HS100 also works correctly with the Kasa app.

Any help is greatly appreciated. Thanks

Apologies if it's something simple I'm doing wrong.

Edit:
My home bridge setup is working when the hs-100 plugin is removed. I'm currently using it to interface with my harmony hub. 

I have also setup the HS100 to the same network as my home bridge and checked it works successfully via the phone app.

Here is my config.json file for reference, I checked it using the http://jsonlint.com site: 

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"

	}],
	"platform": "Hs100"
}

**Comment by jsstelt** [comment]
Try the platform section like this. 

"platforms": [{
	"platform": "HarmonyHub",
	"name": "Harmony Hub"
},
{
"platform": "Hs100"
}],

**Comment by settingup** [comment]
So mine would look like this:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}, {
		"platform": "Hs100"
	}],
}

When I try that in the JSON Validator page it gives the following error:

Error: Parse error on line 13:
...form": "Hs100"	}],}
---------------------^
Expecting 'STRING', got '}'

**Comment by jsstelt** [comment]
Loose the last comma

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [{
"platform": "HarmonyHub",
"name": "Harmony Hub"
}, {
"platform": "Hs100"
}
]
}

**Comment by settingup** [comment]
I managed to get this working eventually, after lots of messing about. I think the answer was to enable remote access in the 'Kasa' app, after that the error messages from homebridge disappeared.

My working config.json file is below:

{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "platforms": [{
                "platform": "HarmonyHub",
                "name": "Harmony Hub"
        }, {
                "platform": "Server",
                "port": 8765,
                "name": "Homebridge Server",
                "log": "systemd",
                "restart": "sudo reboot"
}, {
                "platform": "Hs100"
  }]
}

**Comment by tucknology** [comment]
I'm seeing the same error:

```
Load homebridge-hs100.Hs100
/usr/lib/node_modules/homebridge-hs100/index.js:20
this.plugs = config['plugs'] || [];
^

TypeError: Cannot read property 'plugs' of null
at new Hs100Platform (/usr/lib/node_modules/homebridge-hs100/index.js:20:24)
at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:30)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:8)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
```

I'm pretty sure I have my config.json set up correctly, based on my understanding of JSON, the jsonlint.com verification, and the above discussion.

```
{
	"bridge": {
		HIDDEN FOR PRIVACY
	},

	"platforms": [{
		"platform": "Foo",
		"name": "Foo",
		"fooProperty": [{
			"username": "username",
			"password": "password",
			"host": "127.0.0.1"
		}, {
			"platform": "Hs100"
		}]
	}],

	"accessories": [{
		"accessory": "fooAccessory",
		"name": "fooName",
		"fooProperty": 14
	}]
}
```

(I've modified portions for my security and privacy.)

I've tried enabling remote access using the Kasa app, and it doesn't seem to solve the problem for me. Any ideas?

**Comment by tucknology** [comment]
It seems there is a bug in version 2.0.0. I have a [suggested temporary workaround here](https://github.com/plasticrake/homebridge-hs100/issues/17#issuecomment-286638159).

**Comment by jsstelt** [comment]
I have version 2.0 but still problems with auto discovery

**Comment by tucknology** [comment]
@jsstelt Did you try using [version 1.1.1](https://github.com/plasticrake/homebridge-hs100/issues/17#issuecomment-286638159) ?

**Comment by leematt** [comment]
@tucknology Your JSON is technically valid, but you have the `Hs100` platform nested inside the `Foo` platform:

```
"platforms": [{
		"platform": "Foo",
		"name": "Foo",
		"fooProperty": [{
			"username": "username",
			"password": "password",
			"host": "127.0.0.1"
		}, {
			"platform": "Hs100"
		}]
	}]
```

Try this instead:

```
"platforms": [{
		"platform": "Foo",
		"name": "Foo",
		"fooProperty": [{
			"username": "username",
			"password": "password",
			"host": "127.0.0.1"
		}]
	},
	{
		"platform": "Hs100"
	}]
```

I have also provided some solutions to this problem in another issue: https://github.com/plasticrake/homebridge-hs100/issues/17#issuecomment-292381483
