### ISSUE TITLE
Update V2.1.0 problem arises

### ISSUE THREAD

**Issue by shidevil** [plasticrake/homebridge-hs100#21]
Hi,

Great update to V2.1.0. However there is some issue after upgrading that causes the plugin not to work. 

After upgrading using sudo npm -g update homebridge-hs100

The plugin stop working due to plug.js from the hs100 API 
`this.supportsConsumption = (sysInfo.feature.includes('ENE'));`

I went to lib/plug.js to remove that line, this.emitevents() and corresponding functions that uses supports consumption and it works.

**Comment by plasticrake** [comment]
Do you get an error message? What version of Node are you using?

**Comment by shidevil** [comment]
My node version is v7.10.0

Yes i did receive an error message which is the above but not the full log. Let me get the full log and put it up here

**Comment by shidevil** [comment]
Hi this is the log after updating to V2.1.0 

```
Aug 13 03:30:22 raspberrypi homebridge[13605]: [8/13/2017, 3:30:22 AM] New Plug Online: Fan [<ommited>]
Aug 13 03:30:22 raspberrypi homebridge[13605]: [8/13/2017, 3:30:22 AM] Configuring: Fan
Aug 13 03:30:22 raspberrypi homebridge[13605]: /usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/plug.js:63
Aug 13 03:30:22 raspberrypi homebridge[13605]: this.supportsConsumption = (sysInfo.feature.includes('ENE'));
Aug 13 03:30:22 raspberrypi homebridge[13605]: ^
Aug 13 03:30:22 raspberrypi homebridge[13605]: TypeError: Cannot read property 'includes' of undefined
Aug 13 03:30:22 raspberrypi homebridge[13605]: at Plug.set sysInfo [as sysInfo] (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/plug.js:63:48)
Aug 13 03:30:22 raspberrypi homebridge[13605]: at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/client.js:84:22)
Aug 13 03:30:22 raspberrypi homebridge[13605]: at emitTwo (events.js:106:13)
Aug 13 03:30:22 raspberrypi homebridge[13605]: at Socket.emit (events.js:194:7)
Aug 13 03:30:22 raspberrypi homebridge[13605]: at UDP.onMessage (dgram.js:544:8)
```

**Comment by plasticrake** [comment]
Should be fixed in 2.2.0

**Comment by shidevil** [comment]
Will test it later!

**Comment by shidevil** [comment]
@plasticrake working fine on v2.2.0! great work thank you!
