### ISSUE TITLE
Error starting homebridge - Duplicate UUID

### ISSUE THREAD

**Issue by christianbain** [plasticrake/homebridge-hs100#22]
Below is the error I am getting from Homebridge.  I have HS100 plugs configured in Kasa.  Thoughts?

8/15/2017, 2:41:06 AM] [Kasa] Adding: CameraControl

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:76
      throw new Error("Cannot add a Characteristic with the same UUID as another Characteristic in this Service: " + existing.UUID);
            ^
Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000052-0000-1000-8000-0026BB765291
    at Service.AccessoryInformation.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:76:13)
    at Hs100Platform.addAccessory (/usr/lib/node_modules/homebridge-hs100/index.js:81:17)
    at Client.Hs100Platform.client.on (/usr/lib/node_modules/homebridge-hs100/index.js:50:14)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/client.js:87:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage (dgram.js:544:8)

**Comment by kevvok** [comment]
The issue seems to be caused by an update to https://github.com/KhaosT/HAP-NodeJS/commit/30f0aadc1613863e1590a6132484da92e617e385 that was just pulled in by Homebridge. It added Characteristic.FirmwareRevision to Service.AccessoryInformation as a mandatory Characteristic. I tried commenting out line 81 and was able to start up Homebridge successfully and have it add my HS110 plug.

**Comment by christianbain** [comment]
Ok.  I commented out that line (actually did 81 and 82 prior to reading your message), and that got around the problem.

**Comment by plasticrake** [comment]
Thanks! I upgraded my homebridge, HAP-NodeJS to the latest versions and released a new version of this, and now only adding these new characteristics if they are missing.

**Comment by ZookeRooi** [comment]
I have installed the new version (thanks) and ran it on my Raspberry: 

Loaded config.json with 2 accessories and 1 platforms.
_[8/17/2017, 7:24:41 AM] ---
[8/17/2017, 7:24:41 AM] Loading 1 platforms...
[8/17/2017, 7:24:41 AM] Initializing Hs100 platform...
[8/17/2017, 7:24:41 AM] Loading 2 accessories..._

After that however, the HS100 accessory is nog added within my Insteon app as a device and therefor not in my Homekit. Am I doing something wrong?
