### ISSUE TITLE
Not available in HomeKit 

### ISSUE THREAD

**Issue by ZookeRooi** [plasticrake/homebridge-hs100#24]
I have installed the latest version, using node 6.11.2. However, after the complete installation and restarting Homebridge, the HS100 is not popping up in Insteon+ and therefore not in HomeKit. What am I doing wrong?

Can anyone please help me?

**Comment by ZookeRooi** [comment]
[8/20/2017, 11:21:51 AM] Loaded plugin: homebridge-soundtouch
[8/20/2017, 11:21:51 AM] Registering accessory 'homebridge-soundtouch.SoundTouch'
[8/20/2017, 11:21:51 AM] ---
[8/20/2017, 11:21:51 AM] Loaded config.json with 2 accessories and 1 platforms.
[8/20/2017, 11:21:51 AM] ---
[8/20/2017, 11:21:51 AM] Loading 1 platforms...
[8/20/2017, 11:21:51 AM] Initializing Hs100 platform...
[8/20/2017, 11:21:51 AM] Loading 2 accessories...
[8/20/2017, 11:21:51 AM] [Speaker Woonkamer] Initializing SoundTouch accessory...
Started Searching...
[8/20/2017, 11:21:51 AM] [thermostaat] Initializing NefitEasy accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by ZookeRooi** [comment]
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/20/2017, 8:24:04 PM] Loaded plugin: homebridge-hs100
[8/20/2017, 8:24:04 PM] Registering platform 'homebridge-hs100.Hs100'
[8/20/2017, 8:24:04 PM] ---
[8/20/2017, 8:24:05 PM] Loaded plugin: homebridge-nefit-easy
[8/20/2017, 8:24:05 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[8/20/2017, 8:24:05 PM] ---
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/20/2017, 8:24:06 PM] Loaded plugin: homebridge-soundtouch
[8/20/2017, 8:24:06 PM] Registering accessory 'homebridge-soundtouch.SoundTouch'
[8/20/2017, 8:24:06 PM] ---
[8/20/2017, 8:24:06 PM] Loaded config.json with 2 accessories and 1 platforms.
[8/20/2017, 8:24:06 PM] ---
[8/20/2017, 8:24:06 PM] Loading 1 platforms...
[8/20/2017, 8:24:06 PM] Initializing Hs100 platform...
[8/20/2017, 8:24:06 PM] Loading 2 accessories...
[8/20/2017, 8:24:06 PM] [Speaker Woonkamer] Initializing SoundTouch accessory...
Started Searching...
[8/20/2017, 8:24:06 PM] [thermostaat] Initializing NefitEasy accessory...

**Comment by plasticrake** [comment]
That doesn't look like the full log. I would expect to see `Homebridge is running on port 51826.` I don't think homebridge is finishing setting up. What's that NefitEasy accessory? Try removing those from your config or just use the sample config for homebridge-hs100.

**Comment by ZookeRooi** [comment]
Homebridge is starting:
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
[8/22/2017, 5:35:45 AM] Homebridge is running on port 51826._

The Nefit Easy is my Thermostat.

Thanks for your advice. I will give it a try!

**Comment by ZookeRooi** [comment]
I have uninstalled the Nefit and the Soundtouch so only the HS100 is left. If edited my config.json and restarted Homebrigde. It does not start up:

[8/24/2017, 9:11:23 PM] Loading 1 platforms...
[8/24/2017, 9:11:23 PM] Initializing Hs100 platform...
[8/24/2017, 9:11:23 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 :(

**Comment by plasticrake** [comment]
That error is in homebridge before it even gets to this plugin. What is your config? Did you match the sample in this repo?

**Comment by ZookeRooi** [comment]
This it what  I did:

 I wrote a Raspbian Jessie Image on the SD card and then entered the following lines:

sudo apt-get update

sudo apt-get upgrade

wget https://nodejs.org/dist/v6.11.2/node-v6.11.2-linux-armv6l.tar.xz

tar -xvf node-v6.11.2-linux-armv6l.tar.xz

cd node-v6.11.2-linux-armv6l

sudo apt-get install libavahi-compat-libdnssd-dev

sudo npm install -g homebridge

sudo npm install -g homebridge-hs100_

**Comment by plasticrake** [comment]
you didn't say anything about your config.json

**Comment by ZookeRooi** [comment]
That look's like this:
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

	"accessories": [{
		"accessory": "SoundTouch",
		"name": "Speaker Woonkamer",
		"room": "Woonkamer"
	},{
		"accessory": "NefitEasy",
		"name": "thermostaat",
		"room": "Woonkamer",
		"options": {
			"serialNumber": "XXXXX",
			"accessKey": "XXXXXX",
			"password": "XXXXX"
		}

	}],
	"platforms": [{
"platform": "Hs100"}]
}

**Comment by plasticrake** [comment]
Right, remove those accessories. You should only have the bridge section and the platform.

**Comment by ZookeRooi** [comment]
Tried that but still, it is not working. It dit work with the old version. I will do a new install, leave out the accessoires and only install the HS100. Should work!

**Comment by ZookeRooi** [comment]
I did a complete new and clean install. Ieft out the accessoires and only installed the HS100 by typing sudo npm install -g homebrigde-hs100
After that I entered the config.json as mentioned before and tried starting up homebridge. It did start but still, the HS100 is not popping up:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/27/2017, 11:10:19 AM] Loaded plugin: homebridge-hs100
[8/27/2017, 11:10:19 AM] Registering platform 'homebridge-hs100.Hs100'
[8/27/2017, 11:10:19 AM] ---
[8/27/2017, 11:10:19 AM] Loaded config.json with 0 accessories and 1 platforms.
[8/27/2017, 11:10:19 AM] ---
[8/27/2017, 11:10:19 AM] Loading 1 platforms...
[8/27/2017, 11:10:19 AM] Initializing Hs100 platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/27/2017, 11:10:20 AM] Homebridge is running on port 51826.

**Comment by plasticrake** [comment]
Is the HS100 on the same network as homebridge? When you use the Kasa app on your phone do the devices show up (as local, not remote)?

**Comment by plasticrake** [comment]
I just released a huge rewrite of the API and this plugin. Please update and try again. Run `DEBUG=* homebridge --debug` to get better output. 

Also I created a CLI to help debug. `npm install -g h100-api` then run `hs100-api search`
