### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by AlexGustafsson** [plasticrake/homebridge-hs100#27]
Running 3.0.0 the following error occurs:
```
/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2924d09e-3d10-4728-a9e2-fd73ddd3e279
    at Bridge.Accessory.addBridgedAccessory (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:283:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/api.js:159:8)
    at Hs100Platform.registerPlatformAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:46:14)
    at new PlugAccessory (/homebridge/node_modules/homebridge-hs100/lib/plug.js:23:21)
    at Hs100Platform.addAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:77:27)
```

Full log:
```
[9/6/2017, 10:26:25 PM] Loaded plugin: homebridge-hs100
[9/6/2017, 10:26:25 PM] Registering platform 'homebridge-hs100.Hs100'
[9/6/2017, 10:26:25 PM] ---
[9/6/2017, 10:26:25 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/6/2017, 10:26:25 PM] ---
[9/6/2017, 10:26:26 PM] Loading 1 platforms...
[9/6/2017, 10:26:26 PM] Initializing Hs100 platform...
[9/6/2017, 10:26:26 PM] Configuring cached accessory: [Lamp1]
[9/6/2017, 10:26:26 PM] Configuring cached accessory: [Lamp2]
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/6/2017, 10:26:26 PM] Homebridge is running on port 51826.
DEBUG - {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.0.8 Build 151101 Rel.24452","hw_ver":"1.0","type":"smartplug","model":"HS110(EU)","mac":"[removed]","deviceId":"[removed]","hwId":"[removed]","fwId":"[removed]","oemId":"[removed]","alias":"Lamp1","dev_name":"Wi-Fi Smart Plug With Energy Monitoring","icon_hash":"","relay_state":1,"on_time":12281,"active_mode":"schedule","feature":"TIM:ENE","updating":0,"rssi":-29,"led_off":0,"latitude":[removed],"longitude":[removed]}}} from 192.168.1.99
DEBUG: plug set sysInfo()
DEBUG: device set sysInfo()
DEBUG: plug emitEvents()
DEBUG: plug get sysInfo()
DEBUG: device get sysInfo()
DEBUG: emitEvents() inUse: false powerOn: true lastState: {"powerOn":null,"inUse":null}
DEBUG: plug emitEvents()
DEBUG: plug get sysInfo()
DEBUG: device get sysInfo()
DEBUG: emitEvents() inUse: false powerOn: true lastState: {"powerOn":true,"inUse":false}
DEBUG: plug set sysInfo()
DEBUG: device set sysInfo()
DEBUG: plug emitEvents()
DEBUG: plug get sysInfo()
DEBUG: device get sysInfo()
DEBUG: emitEvents() inUse: false powerOn: true lastState: {"powerOn":true,"inUse":false}
DEBUG: plug emitEvents()
DEBUG: plug get sysInfo()
DEBUG: device get sysInfo()
DEBUG: emitEvents() inUse: false powerOn: true lastState: {"powerOn":true,"inUse":false}
[9/6/2017, 10:26:26 PM] New Device Online: [Lamp1] device [removed id]
[9/6/2017, 10:26:26 PM] Adding: [Lamp1] device [removed id]
/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2924d09e-3d10-4728-a9e2-fd73ddd3e279
    at Bridge.Accessory.addBridgedAccessory (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:283:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/api.js:159:8)
    at Hs100Platform.registerPlatformAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:46:14)
    at new PlugAccessory (/homebridge/node_modules/homebridge-hs100/lib/plug.js:23:21)
    at Hs100Platform.addAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:77:27)
Got SIGTERM, quitting.
```

**Comment by plasticrake** [comment]
Try `rm -rf ~/.homebridge/persist && rm -rf ~/.homebridge/accessories` or wherever your config files are stored.

**Comment by AlexGustafsson** [comment]
That semt like the logical cause and I've tried clearing the folder, as well as clearing out all node modules and reinstalling. Neither was successful in letting me run homebridge without the error.

**Comment by jonfairbanks** [comment]
Stuck on this same issue unfortunately. Let me know if I can help with any additional details. 

```
[9/7/2017, 12:58:58 AM] [homebridge-hs100.Hs100] Adding: [Bedroom Lights] plug <plug id>
/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257
throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
```

**Comment by plasticrake** [comment]
Clear cached data:
 `rm -rf ~/.homebridge/persist && rm -rf ~/.homebridge/accessories`

Remove `debug: true` from your hs100 platform config

Run and post the output:
`homebridge --debug`
(if you see `Configuring cached accessory` that means you didn't clear the cached data.)

Install/run and post the output: `hs100-api search`

If you're going to remove the deviceIds from the output at least ensure they are unique as that as what we generate the UUID from.

**Comment by AlexGustafsson** [comment]
It seems like there was persistent folders left behind my deletion even though I was sure I double-checked. Removing all the mentioned folders I came a bit further before the plugin threw me out.

My config.json no longer contains `debug: true`.

`DEBUG=* homebridge` log: (I cannot run `homebridge debug` easily due to the server environment`) 
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.0
npm info ok 
[9/7/2017, 7:16:21 PM] Loaded plugin: homebridge-hs100
[9/7/2017, 7:16:21 PM] Registering platform 'homebridge-hs100.Hs100'
[9/7/2017, 7:16:21 PM] ---
[9/7/2017, 7:16:21 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/7/2017, 7:16:21 PM] ---
[9/7/2017, 7:16:21 PM] Loading 1 platforms...
[9/7/2017, 7:16:21 PM] Initializing Hs100 platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Thu, 07 Sep 2017 17:16:21 GMT Accessory [Homebridge] Creating new AccessoryInfo for our HAP server
Thu, 07 Sep 2017 17:16:21 GMT Accessory [Homebridge] Creating new IdentifierCache
Thu, 07 Sep 2017 17:16:21 GMT EventedHTTPServer Server listening on port 51826
[9/7/2017, 7:16:21 PM] Homebridge is running on port 51826.
[9/7/2017, 7:16:21 PM] New Device Online: [Lamp1] device [removed 22 character id]
[9/7/2017, 7:16:21 PM] Adding: [Lamp1] device [removed 22 character id - same as above]
/homebridge/node_modules/homebridge-hs100/lib/plug.js:34
    this.outletService.getCharacteristic(Characteristic.On)
                      ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at new PlugAccessory (/homebridge/node_modules/homebridge-hs100/lib/plug.js:34:23)
    at Hs100Platform.addAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:77:27)
    at Client.Hs100Platform.client.on (/homebridge/node_modules/homebridge-hs100/lib/platform.js:23:12)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.emit (/homebridge/node_modules/hs100-api/lib/client.js:102:13)
    at Socket.socket.on.e (/homebridge/node_modules/hs100-api/lib/client.js:206:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)
Got SIGTERM, quitting.
```
_The removed id is the same in every mention of it in the log._

`hs-100api search` output:
```
Searching...
HS110(EU) device 192.168.1.99 [removed id, never mentioned in the homebridge log. 22 characters]
HS110(EU) device 192.168.1.218 [same id as in the homebridge log for Lamp1]
```

**Comment by plasticrake** [comment]
@AlexGustafsson try upgrading to 3.1.0. Not sure how I didn't catch that.

**Comment by AlexGustafsson** [comment]
It now works as expected. I'm excited to see if all your changes brings better reliability to the plugin!
Thanks for responsive and continuous support :smile:.

Fixed in 3.1.0.

**Comment by nicoduj** [comment]
I made a new install of homebridge and this plugin with 2 HS100 plugs : I had the same problem after each restart of my docker image (installation on synology with docker). I had to remove the cached directory before being able to restart it. I then put static ip to the plugs. I am not sure if the problem occured again because of names change in Home app on IOS or because of the ip change with DHCP renew last night, however this problem seems to appear again in latest version in some conditions.

**Comment by plasticrake** [comment]
@nicoduj you're responding to a closed issue, can you submit this as a new one? I am now starting to see behavior like you describe and it didn't used to be like this. I'm not sure if its a homebridge issue or with the plugin. If you can post the startup log info that would be helpful too. I see this:

```
[TplinkSmarthome] Configuring cached accessory: [Test] 8006FF769E5C9248D4E4266B3B1344D8173F7DCA 7dd5f666-53f0-4
[TplinkSmarthome] Configuring cached accessory: [Living Room Fan] 80061DB94A7B919930FA4AE280CBDC9F1749CD14 2f4b
[TplinkSmarthome] Configuring cached accessory: [My Smart Bulb] 801279C8E7092E3AF5FEDCB54056CE6E185998AA 35bbd3
[TplinkSmarthome] Configuring cached accessory: [Bedroom Fan] 80068010F85DB167FAA7303A63183B83174914A3 73e6fabe
[TplinkSmarthome] Configuring cached accessory: [Bathroom Fan] undefined feffd314-f1c7-43a2-96a3-459a0ffa8474

...

[TplinkSmarthome] New Device Online: [Bedroom Fan] plug [80068010F85DB167FAA7303A63183B83174914A3] 10.0.0.118 9
[TplinkSmarthome] Adding: [Bedroom Fan] plug [80068010F85DB167FAA7303A63183B83174914A3]
[TplinkSmarthome] New Device Online: [Bathroom Fan] plug [80066A3C8B9500CF3B95D595FDEF005B18AF176A] 10.0.0.107
[TplinkSmarthome] Adding: [Bathroom Fan] plug [80066A3C8B9500CF3B95D595FDEF005B18AF176A]
 /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257
Dec 01 08:43:31 peridot homebridge[7109]:       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
```


Notice the "undefined" as the deviceId from the cache, so it tries to add it again. Would like to know if you're seeing something similar.

**Comment by nicoduj** [comment]
Done ! Issue#46

Nicolas

Le 3 déc. 2017 à 20:25, Patrick Seal <notifications@github.com<mailto:notifications@github.com>> a écrit :


@nicoduj<https://github.com/nicoduj> you're responding to a closed issue, can you submit this as a new one? I am now starting to see behavior like you describe and it didn't used to be like this. I'm not sure if its a homebridge issue or with the plugin. If you can post the startup log info that would be helpful too. I see this:

[TplinkSmarthome] Configuring cached accessory: [Test] 8006FF769E5C9248D4E4266B3B1344D8173F7DCA 7dd5f666-53f0-4
[TplinkSmarthome] Configuring cached accessory: [Living Room Fan] 80061DB94A7B919930FA4AE280CBDC9F1749CD14 2f4b
[TplinkSmarthome] Configuring cached accessory: [My Smart Bulb] 801279C8E7092E3AF5FEDCB54056CE6E185998AA 35bbd3
[TplinkSmarthome] Configuring cached accessory: [Bedroom Fan] 80068010F85DB167FAA7303A63183B83174914A3 73e6fabe
[TplinkSmarthome] Configuring cached accessory: [Bathroom Fan] undefined feffd314-f1c7-43a2-96a3-459a0ffa8474

...

[TplinkSmarthome] New Device Online: [Bedroom Fan] plug [80068010F85DB167FAA7303A63183B83174914A3] 10.0.0.118 9
[TplinkSmarthome] Adding: [Bedroom Fan] plug [80068010F85DB167FAA7303A63183B83174914A3]
[TplinkSmarthome] New Device Online: [Bathroom Fan] plug [80066A3C8B9500CF3B95D595FDEF005B18AF176A] 10.0.0.107
[TplinkSmarthome] Adding: [Bathroom Fan] plug [80066A3C8B9500CF3B95D595FDEF005B18AF176A]
 /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257
Dec 01 08:43:31 peridot homebridge[7109]:       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);


Notice the "undefined" as the deviceId from the cache, so it tries to add it again. Would like to know if you're seeing something similar.
