### ISSUE TITLE
TPLink Device TCP Timeout and this.log.trace is not a function

### ISSUE THREAD

**Issue by AlexGustafsson** [plasticrake/homebridge-hs100#28]
Related or unrelated, but this occurred when spamming the switch on and off via Home.

```
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/7/2017, 9:32:06 PM] Homebridge is running on port 51826.
[9/7/2017, 9:32:06 PM] New Device Online: [Lamp 2] device [removed lamp 2 id]
[9/7/2017, 9:32:06 PM] Adding: [Lamp 2] device [removed lamp 2 id]
[9/7/2017, 9:32:06 PM] New Device Online: [Lamp1] device [removed lamp1 id]
[9/7/2017, 9:32:06 PM] Adding: [Lamp1] device [removed lamp1 id]
[9/8/2017, 9:47:34 AM] TPLink Device TCP timeout
[9/8/2017, 9:47:34 AM] [Lamp1] setPowerState
[9/8/2017, 9:47:34 AM] Error: TPLink Device TCP timeout
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:79:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[9/8/2017, 9:47:36 AM] TPLink Device TCP timeout
[9/8/2017, 9:47:36 AM] [Lamp1] setPowerState
[9/8/2017, 9:47:36 AM] Error: TPLink Device TCP timeout
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:79:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[9/8/2017, 9:47:39 AM] TPLink Device TCP timeout
[9/8/2017, 9:47:39 AM] [Lamp1] setPowerState
[9/8/2017, 9:47:39 AM] Error: TPLink Device TCP timeout
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:79:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[9/8/2017, 9:47:42 AM] TPLink Device TCP timeout
[9/8/2017, 9:47:42 AM] [Lamp1] setPowerState
[9/8/2017, 9:47:42 AM] Error: TPLink Device TCP timeout
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:79:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[9/8/2017, 9:47:45 AM] TPLink Device TCP timeout
[9/8/2017, 9:47:45 AM] [Lamp1] setPowerState
[9/8/2017, 9:47:45 AM] Error: TPLink Device TCP timeout
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:79:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[9/8/2017, 9:48:02 AM] TPLink Device TCP error
/homebridge/node_modules/hs100-api/lib/client.js:84
        this.log.trace(err);
                 ^

TypeError: this.log.trace is not a function
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:84:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at writeAfterEnd (_stream_writable.js:195:10)
    at Socket.Writable.write (_stream_writable.js:240:5)
    at Socket.write (net.js:657:40)
    at Socket.socket.on (/homebridge/node_modules/hs100-api/lib/client.js:48:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:10)
Got SIGTERM, quitting.
```
Any following start is accompanied with the following log:
```
[9/8/2017, 9:58:24 AM] Configuring cached accessory: [Lamp2]
[9/8/2017, 9:58:24 AM] Configuring cached accessory: [Lamp1]
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/8/2017, 9:58:24 AM] Homebridge is running on port 51826.
[9/8/2017, 9:58:24 AM] New Device Online: [Lamp1] device [removed lamp1 id]
[9/8/2017, 9:58:24 AM] Adding: [Lamp1] device [removed lamp1 id]
/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: [removed uuid]
    at Bridge.Accessory.addBridgedAccessory (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:283:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:188:7)
    at API.registerPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/api.js:159:8)
    at Hs100Platform.registerPlatformAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:47:14)
    at new PlugAccessory (/homebridge/node_modules/homebridge-hs100/lib/plug.js:24:21)
    at Hs100Platform.addAccessory (/homebridge/node_modules/homebridge-hs100/lib/platform.js:78:27)
Got SIGTERM, quitting.
```

**Comment by plasticrake** [comment]
I'm not able to reproduce your timeouts (I can turn my plugs on and off rapidly for 20 seconds and no issues). But that error shouldn't have happened (due to the trace). Release version 3.2.0 that fixes that trace and has lots of other changes and features!
